modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="manicworld"
version="${file.jarVersion}"
displayName="Manic World"
displayURL="https://github.com/DavidQF555/ManicWorld"
authors="DavidQF555"
description='''
This mod creates a manic world filled with more mobs and items.
'''